### ISSUE TITLE
Upgrade to Bootstrap 5.2

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#247]
@Harvey1214 lets get ready for the Bootstrap 5.2 stable version and create a branch for testing 5.2-beta1.

- [x] Add possibility to set `Offcanvas` responsive classes (the responsive classes are substitutions to the `offcanvas` class)
- [x] Review our implementation of `HxScrollspy` and its JS Interop as it has been rewritten in 5.2
- [x] Decide wether we want an API for `form-check-reverse` or using of `CssClass` is enough
- [x] Lets try to get rid of our custom Bootstrap build in favour of CSS variables
- [x] Update links to getbootstrap.com to the 5.2 version of the doc
- [x] `HxInputDateRange` both the second input and the predefined dates context menu open calendars controlling the range's start value, overall strange behavior probably caused by one dropdown wrapping all dropdown menus and toggles (which is probably necessary for input group behavior
- [x] `HxOffcanvas` static backdrop
- [x] `HxInputDate` when the three dots are clicked, a calendar is opened
- [x] `HxOffcanvas` not opening in custom build

**Comment by Harvey1214** [comment]
@crdo I'm starting to doubt the decision to scrap our Bootstrap build and use CSS variables instead.

Correct me if I'm wrong, however, I don't think there's a way to set the box shadow (and other common properties) of inputs, accordions, buttons, etc. globally, therefore it's necessary to go through each and every component and set these manually, which can become quite time consuming considering the number of components and CSS variables that need adjustment.

Consider for example the accordion component. A large proportion of these variables' values need to be adjusted solely because we want to change the website's primary color.

![image](https://user-images.githubusercontent.com/62853076/180760867-25e70b30-849d-44dd-98e6-0b80ac0af5e2.png)

Please let me know what you think. Thanks 😉

**Comment by crdo** [comment]
Yes, you are right, the customisation via CSS vars only is not enough for our use case. You can use it for small changes here and there but not for the whole HAVIT Blazor theme.

**Comment by Harvey1214** [comment]
@crdo will you create our custom Bootstrap build for the new version, or should I create it?

**Comment by crdo** [comment]
@Harvey1214 lets have a quick meeting and you can go ahead.

**Comment by Harvey1214** [comment]
@crdo sure, I suggest a Teams call tomorrow at 13:00.
