### ISSUE TITLE
`JSDisconnectedException` occurred in .NET6

### ISSUE THREAD

**Issue by rqx110** [havit/Havit.Blazor#298]
when we call `await jsModule.InvokeVoidAsync("dispose", elementReference);` in dispose stage, it may cause `JSDisconnectedException` exception in **.net6**, refer to https://github.com/dotnet/aspnetcore/issues/33336

I create an issue before, see #289

**Comment by hakenr** [comment]
@rqx110 Although the #289 refers to `HxDropdown` I consider it being a repro for the whole `JSDisconectedException` issue we have to solve in all components calling JS from disposal logic.

This issue is duplicate to #289 and I'm closing it.
If I did not get the point, feel free to add comment to explain the difference and I will reopen this issue again.
