### ISSUE TITLE
CSS selectors with .hx-icon selector will not work when custom render component for icons is used which does not set .hx-icon class

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#400]
CSS styles in Havit.Blazor should not use `.hx-icon` selector since it is not guaranteed that HxIcon component will render element with `.hx-icon` class because the whole rendering process of icons is customizable.

Cc: @jirikanda

**Comment by crdo** [comment]
@hakenr @jirikanda there are several places where the icons are hard-coded and so there is no issue (eg. HxChipList and its remove button icon).
The problem is on two places where we allow to set the icons via Settings/Defaults.
- [ ] HxAutosuggestInputInternal ClearIconEffective and SearchIconEffective
- [ ] HxGrid SortDescendingIcon and SortAscendingIcon

**Comment by hakenr** [comment]
For now, I'm closing this issue as obsolete. If it turns out to be an issue again, we can reopen and resolve it.
