### ISSUE TITLE
[HxCarousel] - Disabling automatic sliding makes it flash between slides

### ISSUE THREAD

**Issue by Arnnes** [havit/Havit.Blazor#445]
When using **HxCarousel** and setting the parameter Interval to null to disable automatic sliding, it starts flashing between slides. It can be reproduced on documentation page https://havit.blazor.eu/components/HxCarousel

**Comment by hakenr** [comment]
It turns out that the Bootstrap implementation was adjusted somewhere in between 5.0 and 5.2 and for now, the way to disable automatic sliding is to set `Ride="CarouselRide.False"` (no need to set the `Interval`).

During the testing I found a bug in passing the `CarouselRide` parameter value to the underlying Bootstrap component.
The bug is fixed now and the fix will be included in next release (probably today).
