### ISSUE TITLE
[HxMultiSelect] Keyboard navigation causes whole page to scroll

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#463]
If I hit Up/Down keyboard when HxMultiSelect the whole page scrolls.
I guess it doesn't stop the keyboard event propagation.

**Comment by Harvey1214** [comment]
Hello @crdo,

this happens when none of the items in the dropdown menu are focused, it's not caused by the absence of keyboard event stop propagation attributes.

The user can easily focus the items by pressing tab, therefore I don't consider this to be an issue.

If you still find this to be an issue, we can automatically put focus on the first item using JS when the dropdown menu opens.
