### ISSUE TITLE
[HxInputBase] Input components are not marked correctly when filtered collection is edited

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#494]
### Observed behavior
Let's have a form for editing elements in a collection (the full source code - [MisplacedValidation.razor.txt](https://github.com/havit/Havit.Blazor/files/10930666/MisplacedValidation.razor.txt) - extension changed to meet github rules):

        foreach (var item in school.Students.Where(x => !currentClass.HasValue || x.ClassNo==currentClass.Value))
        {
            <HxInputText @bind-Value="item.Name" Label='@($"Id={item.Id}")' />
        }
The length of the Name property is validated with FluentValidation. When the form is validated the text box is marked and the message is shown. 
![image](https://user-images.githubusercontent.com/39948593/224004689-fdb11780-2aeb-402c-b1d3-18cbaea94b30.png)

When the collection is filtered  (by setting` currentClass=2`), the message is shown correctly but the border of the text box doesn't indicate an error
![image](https://user-images.githubusercontent.com/39948593/224004886-06de3179-ca3d-45a8-905b-cbc13859b474.png)

It doesn't matter whether the filtering is done before or after the validation, but it must occur after the form is rendered. In more complex scenarios it is even possible that valid elements are marked incorrect. The validation message is always shown correctly. I was not able to reproduce the problem on flat class properties (without a collection).

### Source code debugging
The problem was debugged with source code of the library and it was found that the problem is caused by using inconsistent key for filtering  the form messages collection.
To find validation messages the key is constructed from `ValueExpression`  which is passed through parameter `For` (https://github.com/havit/Havit.Blazor/blob/master/Havit.Blazor.Components.Web.Bootstrap/Forms/HxValidationMessage.razor.cs#L86)

     fieldIdentifiers = new[] { FieldIdentifier.Create(For) };

https://github.com/havit/Havit.Blazor/blob/master/Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputBase.cs#L319

     builder.AddAttribute(3, nameof(HxValidationMessage<TValue>.For), ValueExpression);

The variable `FieldIdentifier` is used to find whether the error CSS class should be added (https://github.com/havit/Havit.Blazor/blob/master/Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputBase.cs#L435)

     private protected bool IsValueInvalid() => EditContext.GetValidationMessages(FieldIdentifier).Any();

the problem is that the `FieldIdentifier` variable is connected with different element of the collection (probably the previous one).
### Solution?
When the line mentioned above line is changed to 

    private protected bool IsValueInvalid() => EditContext.GetValidationMessages(FieldIdentifier.Create(ValueExpression)).Any();

the problem seems to be corrected.
### Version information
The problem was observed when validating elements of filtered collection in HxGrid on nuget 3.2.7 and was debugged on current source code. The testing was done with .net 6 and .net 7.

**Comment by hakenr** [comment]
@TPIvan, thank you for the detailed description of the issue and your comprehensive investigation.

While the code change you suggested might partially address the problem, I believe the root cause lies in the design of Blazor's `InputBase`. It seems `InputBase` doesn't anticipate changes to the `EditContext`'s model, and altering the collection, as in your case, is essentially a form of model change.

The [`InputBase:OnParametersSet()` method sets the `FieldIdentifier` property](https://github.com/dotnet/aspnetcore/blob/e1758535a7f9922a61a919ebbc26be06f70fa5a1/src/Components/Web/src/Forms/InputBase.cs#L224-L256). Not using this property in the single place proposed (`IsValueInvalid()`) won't resolve the issue that `FieldIdentifier` will still reference an incorrect collection item after any filtering or sorting and usages of `FieldIdentifier` will fail in other parts of the code.

Currently, the only workaround is to use the `@key` directive for components within iterations. In your scenario, you should modify your code as follows:
```razor
foreach (var item in school.Students.Where(x => !currentClass.HasValue || x.ClassNo == currentClass.Value))
{
    <HxInputText @key="item" @bind-Value="item.Name" Label='@($"Id={item.Id}")' />
}
```
By the way, we're not alone in encountering this issue. You can see a similar discussion and the same `@key` solution suggested at https://github.com/dotnet/aspnetcore/issues/22355.

**Comment by TPIvan** [comment]
I have tested the modified code:

         @foreach (var item in (school ?? new School() { Students = new() }).Students.Where(x => !currentClass.HasValue || x.ClassNo==currentClass.Value))
         {
              <HxInputText @key="@("xx"+item.Id)" @bind-Value="item.Name" Label='@($"Id={item.Id}")' />
         }
and it behaves correctly. So I confirm that the solution/workaround is correct.
