### ISSUE TITLE
[HxAccordion] Disable accordion item

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#495]
I would like an options to specify via a parameter that a specific HxAccordionItem is disabled -> not clickable and the toggle icon is hidden.

Currently I am able to achieve my desired behavior with CSS by setting pe-none on the AccordionItem and by setting display: none on the toggle icon. However I would appreciate a more orthodox way of doing this.

**Comment by hakenr** [comment]
From today's LDM: This can be easily achieved with CSS (e.g. `pointer-events:none`) and as there is no official "disabled feature" in Bootstrap, we don't have an ambition to design this on our own.

We might return to this issue in future if it turns out that it is not achievable with simple HTML/CSS, or if it will be needed more frequently.
