### ISSUE TITLE
Possible to use FieldCssClassProvider with Havit?

### ISSUE THREAD

**Issue by nironixon** [havit/Havit.Blazor#518]
Hi there, 
When doing validation of forms I have the need to output some specific CSS classes to know if a specific input field / attribute is modified and if it validates. I've created an an implementation of `Microsoft.AspNetCore.Components.Forms.FieldCssClassProvider` that
works fine when using the `InputText `component from Microsoft. When I try to get the same behaviour but using `HxInputText `from Havit I don't see that my CSS classes being emitted. Does HxInputText work with `Microsoft.AspNetCore.Components.Forms.FieldCssClassProvider` or maybe Im doing something wrong?

My implementation of the custom FieldCssClassProvider looks like:

```
public class CustomFieldClassProvider : FieldCssClassProvider
{
    public override string GetFieldCssClass(EditContext editContext, in FieldIdentifier fieldIdentifier)
    {
        var isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();

        if (editContext.IsModified(fieldIdentifier))
        {
            return isValid ? "modified valid" : "modified invalid";
        }
        else
        {
            return isValid ? "valid" : "invalid";
        }

        return string.Empty;
    }
}
```
Which I hook up to the the given EditForm as: 

```
protected override void OnInitialized()
    {
        editContext = new(exampleModel);
        editContext.SetFieldCssClassProvider(new CustomFieldClassProvider());
        editContext.OnFieldChanged += (_, _) =>
        {
            if (editContext.IsModified())
            {
                if (editContext.Validate())
                {
                    submitClass = "btn enableSubmit";
                    _showValidationSummary = false;
                }
                else
                {
                    submitClass = "btn disableSubmit";
                }
            }

            StateHasChanged();
        };
    }
```

Best Regards
Niclas

**Comment by bluisanajmr** [comment]
I have also been trying to use a CustomFieldClassProvider on an editform with Havit inputs.  My use case is to show a red * on all inputs (on the initial page load) that are required for form submission.  I am using fluent validation which works very well but the recommended method of displaying custom messages or adding custom css according to validation rules is to create a CustomFieldClassProvider for your editform.  I believe your would have the same limitation if you were using the built in DataAnnotations as well.  I couldn't find another acceptable method of accomplishing this without using a CustomFieldClassProvider.  

`public class CustomFieldClassProvider : FieldCssClassProvider
{
    //this is just in place so I can hit a breakpoint to check if class 
    //actuall gets instantiated.  This breakpoint gets hit in my code. 
    string me = "";

    //this method never gets hit
    public override string GetFieldCssClass(EditContext editContext, in FieldIdentifier fieldIdentifier)
        => !editContext.GetValidationMessages(fieldIdentifier).Any()
        ? editContext.IsModified(fieldIdentifier)
        ? "is-valid" : "needs-validation" : "is-invalid";
}`

This is how I call the CustomFieldClassProvider from my component

`_EditContext = new(projectmodel);
_EditContext?.SetFieldCssClassProvider(new CustomFieldClassProvider());`

Then I was going to do something like this for my CSS

'.is-invalid{
content: '*';
color: red;
}'

If the Havit controls fully implemented the CustomFieldClassProvider it would give developers the opportunity to fully customize validation css according to their model validation rules.  Right now I am very limited in how I can display my error messages.  I could of course write code to manually display a red * for all required fields but that requires manually duplicating a ton of code for every model in every page.  This also leads to a maintenance nightmare when I want to change validation rules because I then have to go to every component that uses a model with validation rules and make sure the hardcoded red * matches all of the required rules.

**Comment by hakenr** [comment]
The current implementation of `FieldCssClassProvider` in Blazor is somewhat convoluted. Refer to this issue for more details: [Blazor Issue #34099](https://github.com/dotnet/aspnetcore/issues/34099).

- Currently, there's no straightforward method to replace the default `FieldCssClassProvider`. It requires setting up for every `EditContext` individually.
- Consequently, we can't rely on the `editContext.FieldCssClass()` method effectively. It doesn't indicate if a custom `FieldCssClassProvider` is in use or if the returned CSS class should supersede the default. We shouldn't need to set a specific `HxFieldCssClassProvider` for each `EditContext`.

Given these limitations, we could consider bypassing `editContext.FieldCssClass()` and instead replicate its logic:

```csharp
if (editContext.Properties.TryGetValue(FieldCssClassProviderKey, out var customProvider))
{
    // Retrieve the custom CSS classes from the provider here
}
// Default to Bootstrap CSS classes if no custom FieldCssClassProvider is present
```

However, this approach hits a snag since `FieldCssClassProviderKey` is `private`, blocking this potential workaround.
