### ISSUE TITLE
[HxSidebar] HxSidebar.razor.css contains media query which is not consistent with SidebarResponsiveBreakpoint property.

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#542]
[HxSidebar.razor.css](https://github.com/havit/Havit.Blazor/blob/3b1f17869a5951f66658fb994a2ecbbf5c7ebf9d/Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebar.razor.css#L15) contains the following definition

        @media (min-width: 768px) {
	     .hx-sidebar,
	     .hx-sidebar .nav-menu {
	     max-height: 100vh;
	    }
         }
I have found it when trying to defeat extra scrollbars. When `SidebarResponsiveBreakpoint `is different from its default (`SidebarResponsiveBreakpoint.Medium`) the rules just make harm.

I think that is necessary to define responsive classes for `100vh` - e.g. `vh-lg-100` and use then appropriately.

**Comment by crdo** [comment]
@TPIvan yes, that is what i was trying to explain in https://github.com/havit/Havit.Blazor/issues/532#issuecomment-1535922715. We try to eliminate use of media queries in css isolation as much as possible in favour of responsive utility classes. 

Classes vh-xx-100 does not exist in Bootstrap and thus we cannot use em. Implementing it by our own also doesn't make sense, because we want our library to be useable with any of Bootstraps builds (themes).

**Comment by TPIvan** [comment]
@crdo  ok, now I understand why your comment was so complex. I haven't noticed the current problem in that time. However if I would have noticed it, I would have reported it as a separate issue.

Should this one been closed? Because it is being solved in #532?
