### ISSUE TITLE
HxGrid - System Aggregate Exception

### ISSUE THREAD

**Issue by DaleCam** [havit/Havit.Blazor#55]
First of all I have you thank your team for such an incredible amount of work and excellent documentation! It really is superb! 

I am currently using the HxGrid without it being wrapped in an "if data is not null" block  because i loved the loading skeleton you guys provide. It currently shows the nice "loading" skeleton:
![image](https://user-images.githubusercontent.com/4400216/147984599-69e9d561-bf51-40b4-9a8c-0cced71fd71c.png)
but i get an issue in the console:

Error: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))

 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')

   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)

   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)

   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.InvokeDataProviderInternal(GridDataProviderRequest`1 request)

   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.RefreshPaginationDataCoreAsync(Boolean renderOnSuccess)

   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.OnAfterRenderAsync(Boolean firstRender)

   --- End of inner exception stack trace ---

I am loading the data for the grid like this:
```c#
    protected override async Task OnInitializedAsync()
    {
        vm.data = await _ctx.GetTradeStatistics();
    }
```

**Notes**
* If i wrap the razor grid in an "if data exists" block it works, but i miss out on your skeleton loading.
* The data feeding this grid  is a slow running query (approx 2 second average)  and returns 700 rows if that helps solve it..

**Comment by hakenr** [comment]
Hi @DaleCam,
thanks for the feedback on our component library and documentation.

The exception you met is caused by the fact that the method you use as `<HxGrid DataProvider="SomeMethod" />` returns `GridDataProviderResult` where the `Data` property is `null`. This should never happen (we will probably add some internal check to the code and throw a more helpful exception) as the DataProvider should always return the data to display (It's why it is `async` to be able to `await` the data and render the progress in the meantime. If there are no data, it should return empty enumerable with TotalCount of 0.)

As of your code... I do not have your DataProvider-method, but I guess it just uses the `vm.Data` to return the result. The situation is that `DataProvider` gets called by the `HxGrid` before your `OnInitializedAsync` method sets the `vm.Data` and at that point in time the `vm.Data` is still `null`.

If you want to use `vm.Data` you should not rely on `OnInitializedAsync` to be finished before the data is needed. One of the acceptable patterns might be:
```csharp
private async Task EnsureDataAsync()
{
  vm.Data ??= await _ctx.GetTradeStatistics();
}
protected override async Task OnInitializedAsync() // this might not be needed at all if don't use the vm.Data elsewhere
{
   await EnsureDataAsync();
}
private async Task<GridDataProviderResult<YourItemType>> YourDataProviderMethod(GridDataProviderRequest<YourItemType> request)
{
  await EnsureDataAsync();
  return request.ApplyTo(vm.Data);
}
```
(Note: In some setups you should prevent parallel loading of the data from two triggers. Add protection of your choice to the `EnsureDataAsync` method.)

**Comment by DaleCam** [comment]
Ahh thank you so much that makes so much sense now! Thank you for your fantastic explanation and example code - its now working a treat. My apologies to create you more work! 
(If you get to Budapest any time soon let me know and drinks on me :)
