### ISSUE TITLE
HxModal does not work if inside an owl carousel

### ISSUE THREAD

**Issue by franky1017** [havit/Havit.Blazor#601]
I am referring to this popular owl carousel component -- [owl](https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html)

If one of the elements in the owl carousel has a button click to open an modal, and if that modal is contained inside that same element, then the opened modal is grayed and not clickable.

The workaround is to call an event inside the element and receive that event from the parent page that contains the owl component, open the modal from the parent page works well.

Not a big deal, but thought to let you know. Somehow the owl component and the modal is conflicting.

**Comment by hakenr** [comment]
@franky1017 Thank you for bringing this to our attention. I believe the issue likely lies at the intersection of Owl Carousel and Bootstrap, rather than being solely related to our library. You can find more information on similar issues here: [Owl vs. Bootstrap Modal Issues](https://www.google.com/search?q=owl+vs.+bootstrap+modal)

I'm closing this issue for now. If you think there is anything we should do on our side, feel free to reopen it.
