### ISSUE TITLE
[HxInput] Bound setter not getting called

### ISSUE THREAD

**Issue by diejozef** [havit/Havit.Blazor#71]
Hi,

I ran into a problem after trying to create a formatted text input box using your `HxInputText` component. When typing the same thing into the box, the setter won't be called (which is probably by design), however even after setting the bound variable to something else and calling `StateHasChanged` results in no change whatsoever.

Consider the following example:
```RAZOR
<HxInputText @bind-Value="@TestProp" @onfocusout="FocusOut"/>
```

```CSHARP
private TimeSpan underlyingVar;

private string content;
public string Content
{
	get => this.content;
	set
	{
		this.underlyingVar = SomeParse(value);
		this.content = SomeFormatting(this.underlyingVar);
	}
}

public async Task FocusOut()
{
	this.content = SomeFormatting(this.underlyingVar);
	StateHasChanged();
}
```

My expected result after FocusOut would be a formatted string inside of the text box, however I get the same text that I typed in.

E.g. when I type '24h' into the box and parse, format it, unfocus the input I'd get '24:00:00', this works well for cases where I actually change the value, however when I type '24h' again, I just get stuck with '24h' in the textbox until I type in something that actually changed the underlying variable.

This logic works well in a simple HTML `<input>` although the bound property's setter gets called even if there was no change.

Is there something I could use to achieve the desired result or should I just stick to regular `<input>` ?

Thank you!

**Comment by diejozef** [comment]
This issue seems to be present in other component frameworks as well. [Radzen Numberic Formatted Value](https://blazor.radzen.com/numeric)
The formatted value won't be formatted if the input value is the same.

**Comment by hakenr** [comment]
@jirikanda, can you please take a look and provide an explanation or workaround?
This is a know issue in Blazor inputs, coming from `InputBase`, maybe even deeper (`input` element itself).
There is a demo for this at BlazorTestApp/HxInputTextTest.
Thank you.

**Comment by jirikanda** [comment]
Hi diejozef,

it is easy to achieve the same behavior without FocusOut method.
Try the following demo, enter "20" to the text box again and again. It formats the value to "20h" but only for the first time (the value is not formatted until you enter another value).

```
<HxInputText @bind-Value="@Content" />

@code{
	private TimeSpan underlyingVar;

	private string content;
	public string Content
	{
		get => this.content;
		set
		{
			this.underlyingVar = SomeParse(value);
			this.content = SomeFormatting(this.underlyingVar);			
		}
	}

	private TimeSpan SomeParse(string value) => TimeSpan.FromHours(int.Parse(value.TrimEnd('h')));
	private string SomeFormatting(TimeSpan value) => value.Hours.ToString() + "h";}
}
```

Why this happens?
Imagine, the HxInputText component somewhere inside renders (in brief):
```
<input type="text" ... value="20h" />
```

OK, the _20h_ value is rendered.
You enter the value _20_.
We format the value to _20h_.
And the input should be rendered with _20h_.
```
<input type="text" ... value="20h" />
```
But what happened? This input is not rendered because it contains no change! From the Blazor perspective, the value did not change from the time it was previosly rendered (Blazor does not look for the value to the DOM). Previously, the value was _20h_, now it is _20h_ again. As a result, the input is not updated and the value _20_ remains in the input.

How to solve this?
You need the component somehow to force the value to be updated. Ehm, javascript? No C# developer wants to have dirty hands...
One hack how to force refreshing the component is to use @key directive. Yes, it is a hack which can have side-effects and you need to know what you are doing...

```
<HxInputText @key="@key" @bind-Value="@Content" />

@code{
	private TimeSpan underlyingVar;
	private int key;

	private string content;
	public string Content
	{
		get => this.content;
		set
		{
			this.underlyingVar = SomeParse(value);
			this.content = SomeFormatting(this.underlyingVar);			
			key++;
		}
	}

	private TimeSpan SomeParse(string value) => TimeSpan.FromHours(int.Parse(value.TrimEnd('h')));
	private string SomeFormatting(TimeSpan value) => value.Hours.ToString() + "h";
}
```

**Comment by diejozef** [comment]
@jirikanda thank you for this thorough answer and for the potential solution as well. I didn't know of `@key`, I'll make sure to read up on it. 

Can you perhaps give me an explanation on why this (my very first code snippet) works (without `@key`) when simply using `<input>` ?  Also, why is `StateHasChanged` not sufficient in this case? Isn't that function supposed to 'force' a refresh of the element?

Thank you very much in advance!

**Comment by jirikanda** [comment]
@diejozef 

> why is StateHasChanged not sufficient in this case

Using StateHasChanged you are requesting to update the "current" component. And yes, it should update all child components but the optimalization says: "Hey, the child component has no parameters changed, so let's skip updating of this child component to save some performance, battery, ..."

If you would like to deep dive into the logic "how Blazor determine whether the parameters are changed", start here:  https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs#L545

>  give me an explanation on why this (my very first code snippet) works when simply using <input> 

Because you are skipping the component level of abstraction and the previous explanation with component update does not work here. 

Let's do not continue this tutorial here and let's consider this issue solved.

**Comment by hakenr** [comment]
From my point of view, `StateHasChanged()` is here not strong enough in any case (no matter of the child/parent or parameters here).
Although the component signals to rerender, the result of rendering goes into the virtual DOM.
It is the virtual DOM diff-logic which does not find any differences as it is not aware of the current `value` of the `input`, but compares the new value with the original one which did not change. You have to hack this logic with the `@key` to let the Virtual DOM diff-logic think there is a major change in the Virtual DOM which has to be synchronized to the real DOM.

@jirikanda Am I right?

**Comment by hakenr** [comment]
@diejozef,
we found the reason for this and we are trying to verify the solution with Microsoft ASP.NET Blazor team:
[#40097 InputText and other input components do not use SetUpdatesAttributeName() for two-way binding](https://github.com/dotnet/aspnetcore/issues/40097)

We are currently able to fix this in our components but we want to verify with Blazor team that it does not cause any unwanted side effects (if there is any reason, other than bug, why they do not use the SetUpdatesAttributeName() in built-in Blazor components).

**Comment by hakenr** [comment]
@diejozef, please note, after the fix, you will still have to create a derived component to achieve what you want - override the `FormatValueAsString` method, e.g.:

```csharp
public class MyInputText : HxInputText
{
	protected override string FormatValueAsString(string value)
	{
		if (value == "24h")
		{
			return "24:00:00";
		}
		return value;
	}
}
```

**Comment by hakenr** [comment]
Blazor PR: https://github.com/dotnet/aspnetcore/pull/40234
Havit.Blazor WIP.

**Comment by hakenr** [comment]
...wating for actions in ASP.NET Blazor itself (opened PR) - we want our implementation to be aligned with that.

**Comment by hakenr** [comment]
Fixed in `net8` and Havit.Blazor v4.3.5+.
