### ISSUE TITLE
[HxGrid] Placeholders do not use `ItemCssClass[Selector]`

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#802]
Eg. InvoiceList in Goran:
![image](https://github.com/havit/Havit.Blazor/assets/12828888/fa179806-0480-4ec1-aaa5-5b56866d6def)

**Comment by Harvey1214** [comment]
@hakenr I don't think it is possible to solve the issue this way. We don't have the item (`TItem`), therefore we can't access the `ItemCssClass` using `ItemRowCssClassSelector?.Invoke(item)` (the item is not yet loaded).

The current implementation of `InvoiceList` in Goran handles the issue using placeholders with preset (hard-coded) widths that match the desired widths of the columns. Do you think this is an acceptable solution? If not, then I'll investigate the problem further. To me it seems reasonable since we cannot get the widths of the items before we render them.

![image](https://github.com/havit/Havit.Blazor/assets/62853076/4028ad29-0f63-4469-a430-53ba314db62e)

`ItemRowCssClassEffective` was added to the placeholder `<tr>` elements in `HxGrid` to improve consistency between the placeholder and standard version.
