### ISSUE TITLE
[HxInputDate] Incorrect (doubled?) rendering of floating labels

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#951]
Extracted from #899:
![image](https://github.com/user-attachments/assets/fc5de0c2-8aff-47ce-ada2-7e6fd843acce)

@mmonteagudo I tried replicating the issue from your screenshot since it looks like an obvious bug. Unfortunately, the basic floating label test I ran with `HxInputDate` didn’t reproduce the error.

Could you share the setup or a code snippet that reproduces the issue?

**Comment by hakenr** [comment]
@mmonteagudo Feel free to modify the test I just added in 8aa652173d948c8906707e8675c177ecb590ebb3.

**Comment by mmonteagudo** [comment]
Oh my, sorry, I added all my comments in the commit instead of here:
https://github.com/havit/Havit.Blazor/commit/8aa652173d948c8906707e8675c177ecb590ebb3#commitcomment-149589023
https://github.com/havit/Havit.Blazor/commit/8aa652173d948c8906707e8675c177ecb590ebb3#commitcomment-149589484
https://github.com/havit/Havit.Blazor/commit/8aa652173d948c8906707e8675c177ecb590ebb3#commitcomment-149590513

This replicates the issue, but I think I actually found the bug, I'm running a test and then pushing the PR for your approval, if you see the screenshot below, we are using the LabelType property instead of the LabelTypeEffective

![image](https://github.com/user-attachments/assets/bac539fc-0f52-46f0-9e56-6fe67f46404e)

**Comment by mmonteagudo** [comment]
Confirmed!!! 
Fixed in https://github.com/havit/Havit.Blazor/pull/952
![image](https://github.com/user-attachments/assets/d83ab1d2-c611-42b7-8eda-c5dcbef60090)

**Comment by hakenr** [comment]
@mmonteagudo Good catch!

> I'm not setting the LabelType property, as I'm using the InputDefault as floating for the whole app

You were quick to identify the cause. I knew it had to be `LabelType` instead of `LabelTypeEffective` from the moment I saw the notification from your comment on my smartwatch during a meeting. :-D  
Now that the meeting's over, the PR is already here. Thank you!
